title: Welcome to my Homepage!
author: Phil Wernette
email: pwernette@usgs.gov | wernette@uwindsor.ca
description: > # this means to ignore newlines until "baseurl:"
  Thank you for visiting my homepage. It is a work in progress and will be periodically updated as my research career develops….

# social links
twitter_username: philwernette # DO NOT include the @ character, or else the build will fail!
github_username:  pwernette # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: slate
#remote_theme: pages-themes/midnight@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
