title: Welcome to my Homepage!
author: Phil Wernette, PhD
email: pwernette@usgs.gov | wernette@uwindsor.ca
description: > # this means to ignore newlines until "baseurl:"
  Research Geologist, U.S. Geological Survey
  Adjunct Faculty, University of Windsor
  PhD (Geography), Texas A&M University

# social links
twitter_username: philwernette # DO NOT include the @ character, or else the build will fail!
github_username:  pwernette # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
# remote_theme: pages-themes/hacker@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one
